### ISSUE TITLE
(might be an issme) opening certain .cs files gives you a million errors over missing assemblies

### ISSUE THREAD

**Issue by milly531** [GabeTheFirst/LocalQuest#1]
self explanatory

**Comment by GabeTheFirst** [comment]
I forgot to include that part of setup in the readme sorry 😭 you need to build https://github.com/GabeTheFirst/QuerryNetworking and reference it in LocalQuest

I'll update the readme with better instructions soon

**Comment by GabeTheFirst** [comment]
This is (should be) fixed in the latest commit 👍
